apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-setup-deployment
  labels:
    app: devops-setup-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-setup-deployment
  template:
    metadata:
      labels:
        app: devops-setup-deployment
    spec:
      containers:
      - name: install-anchore
        image: quay.io/openshift/origin-cli:latest
        command: ["bash","-c"]
        args:
        - >-
          cd workspace/devops-setup_yaml/jenkins; 
          oc create -f jenkins-all-in-one-v1alpha2.yaml; 
          oc create -f crds/jenkins_v1alpha2_jenkins_crd.yaml;
          oc create -f crds/openshift_jenkins_v1alpha2_jenkins_cr.yaml;
          cd ../anchore;
          oc create -f . ;
          oc create -f crds/anchore_v1alpha1_anchoreengine_crd.yaml;
          oc create -f crds/anchore_v1alpha1_anchoreengine_cr.yaml;
          oc expose svc anchore-engine-anchore-engine-api;
          cd ..;
          oc new-app -f sonarqube/sonarqube-template.yaml -p SONARQUBE_SERVICE_NAME=sonarqube;
        volumeMounts:
        - name: source
          mountPath: /workspace

      volumes:
      - emptyDir: {}
        name: source

      initContainers:
      - name: git-clone
        image: alpine/git
        command:
        - git
        - clone
        - {{ devops-repository }}
        volumeMounts:
        - name: source
          mountPath: /git
