kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: devops-setup
subjects:
- kind: ServiceAccount
  name: devops-setup
roleRef:
  kind: Role
  name: devops-setup
  apiGroup: rbac.authorization.k8s.io
